// source/frontend/components/AIDecomposerModal.vue
<script setup lang="ts">
import { ref } from 'vue';
import { useTaskStore } from '../stores/taskStore';
import { api } from '../services/api';
import type { DecomposedTaskResult, TaskPriority } from '../types/task';
import { Sparkles, X, Plus, Check, RefreshCw, AlertCircle, ArrowRight } from 'lucide-vue-next';

const emit = defineEmits<{
  (e: 'close'): void;
}>();

const taskStore = useTaskStore();

const goalInput = ref('');
const isLoading = ref(false);
const result = ref<DecomposedTaskResult | null>(null);
const errorMsg = ref<string | null>(null);
const isInserted = ref(false);

const SUGGESTIONS = [
  'Build OAuth2 Google & GitHub authentication flow',
  'Implement real-time WebSocket presence and collaboration',
  'Deploy production Kubernetes cluster with Helm charts',
  'Port legacy state to Vue 3 Composition API and Pinia store',
];

async function handleDecompose(customGoal?: string) {
  const targetGoal = customGoal || goalInput.value;
  if (!targetGoal.trim()) return;
  if (customGoal) goalInput.value = customGoal;

  isLoading.value = true;
  errorMsg.value = null;
  result.value = null;
  isInserted.value = false;

  try {
    const res = await api.decomposeGoal(targetGoal);
    result.value = res;
  } catch (err: any) {
    errorMsg.value = err.message || 'Decomposition engine failure.';
  } finally {
    isLoading.value = false;
  }
}

function handleAcceptAll() {
  if (!result.value || !result.value.subtasks) return;

  // The store refuses every write on a read-only project (INV-15), so without
  // this guard the loop below silently created nothing and we still flashed
  // "Inserted!" and closed — telling the user their subtasks were saved when
  // none were (F-33). Check before writing, and report instead of pretending.
  if (!taskStore.canMutate) {
    errorMsg.value = taskStore.readOnlyReason === 'OFFLINE_SHARED'
      ? 'This project is read-only while you are offline — it has other members. Reconnect to insert these subtasks.'
      : 'No project selected — open or create one before inserting subtasks.';
    return;
  }

  const createdIds: Record<string, string> = {};

  for (const st of result.value.subtasks) {
    const created = taskStore.createTask(st.title, st.priority || 'MEDIUM', 'TODO');
    if (created) {
      createdIds[st.title] = created.id;
      taskStore.updateTask(created.id, {
        description: st.description,
        complexity: st.complexity,
        acceptanceCriteria: st.acceptanceCriteria,
      });
    }
  }

  // Second pass: wire dependencies
  for (const st of result.value.subtasks) {
    if (st.dependsOnTitles && st.dependsOnTitles.length > 0) {
      const myId = createdIds[st.title];
      if (myId) {
        const depIds = st.dependsOnTitles.map((t) => createdIds[t]).filter(Boolean);
        if (depIds.length > 0) {
          taskStore.updateTask(myId, { dependencies: depIds });
        }
      }
    }
  }

  isInserted.value = true;
  setTimeout(() => {
    emit('close');
  }, 1000);
}
</script>

<template>
  <div
    class="fixed inset-0 z-50 bg-slate-900/40 dark:bg-black/75 backdrop-blur-xs flex items-center justify-center p-3 md:p-6"
    @click.self="emit('close')"
  >
    <div class="bg-white dark:bg-slate-900 w-full max-w-2xl rounded-lg p-5 md:p-6 shadow-2xl border border-slate-200 dark:border-slate-800 text-slate-900 dark:text-slate-100 flex flex-col max-h-[90vh]">
      <!-- Header -->
      <div class="flex items-center justify-between pb-3 border-b border-slate-200 dark:border-slate-800">
        <div class="flex items-center gap-2.5">
          <div class="p-2 rounded-lg bg-indigo-50 dark:bg-indigo-500/10 border border-indigo-200 dark:border-indigo-500/30 text-indigo-600 dark:text-indigo-400">
            <Sparkles class="w-5 h-5" />
          </div>
          <div>
            <h2 class="text-sm md:text-base font-semibold text-slate-900 dark:text-slate-100 font-sans">Task Decomposer</h2>
            <p class="text-[11px] text-slate-500 dark:text-slate-400">Break down goals into subtasks and dependencies</p>
          </div>
        </div>
        <button type="button" class="p-1.5 hover:bg-slate-100 dark:hover:bg-slate-800 rounded-md text-slate-400 hover:text-slate-600 dark:hover:text-slate-200 cursor-pointer" @click="emit('close')">
          <X class="w-5 h-5" />
        </button>
      </div>

      <!-- Input Area -->
      <div class="py-4 space-y-3">
        <div class="flex gap-2">
          <input
            v-model="goalInput"
            type="text"
            placeholder="Describe your engineering goal or feature..."
            class="flex-1 bg-slate-50 dark:bg-slate-950 border border-slate-300 dark:border-slate-800 rounded-md px-3.5 py-2 text-xs text-slate-900 dark:text-slate-100 placeholder-slate-400 dark:placeholder-slate-500 focus:outline-none focus:border-indigo-500 font-sans h-8"
            @keydown.enter="handleDecompose()"
          />
          <button
            type="button"
            class="h-8 px-3.5 rounded-md bg-indigo-600 hover:bg-indigo-500 text-white font-mono font-medium text-xs flex items-center gap-1.5 cursor-pointer shadow-xs disabled:opacity-50 shrink-0"
            :disabled="isLoading || !goalInput.trim()"
            @click="handleDecompose()"
          >
            <RefreshCw v-if="isLoading" class="w-3.5 h-3.5 animate-spin" />
            <Sparkles v-else class="w-3.5 h-3.5" />
            <span>{{ isLoading ? 'Decomposing...' : 'Decompose Task' }}</span>
          </button>
        </div>

        <!-- Quick Prompts -->
        <div class="flex flex-wrap gap-1.5 items-center pt-1">
          <span class="text-[11px] text-slate-500 dark:text-slate-400 font-mono">Presets:</span>
          <button
            v-for="s in SUGGESTIONS"
            :key="s"
            type="button"
            class="text-[11px] font-mono px-2 py-1 rounded bg-slate-100 dark:bg-slate-900 border border-slate-200 dark:border-slate-800 hover:border-slate-300 dark:hover:border-slate-700 text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-slate-200 cursor-pointer"
            @click="handleDecompose(s)"
          >
            {{ s }}
          </button>
        </div>
      </div>

      <!-- Result Area -->
      <div class="flex-1 overflow-y-auto space-y-3 pr-1">
        <div v-if="errorMsg" class="p-3 rounded-lg bg-rose-50 dark:bg-rose-950/40 border border-rose-200 dark:border-rose-800 text-rose-700 dark:text-rose-300 flex items-center gap-2 text-xs font-mono">
          <AlertCircle class="w-4 h-4 shrink-0" />
          <span>{{ errorMsg }}</span>
        </div>

        <div v-if="result" class="space-y-3">
          <div class="p-3 rounded-lg bg-slate-50 dark:bg-slate-950 border border-slate-200 dark:border-slate-800">
            <h3 class="text-xs font-bold text-slate-900 dark:text-slate-200 font-mono">{{ result.epicTitle }}</h3>
            <p class="text-xs text-slate-600 dark:text-slate-400 mt-1 leading-relaxed">{{ result.rationale }}</p>
          </div>

          <div class="space-y-2">
            <div
              v-for="(subtask, idx) in result.subtasks"
              :key="idx"
              class="p-3 rounded-lg bg-slate-50/70 dark:bg-slate-900/60 border border-slate-200 dark:border-slate-800 flex flex-col gap-1.5"
            >
              <div class="flex items-center justify-between gap-2">
                <span class="font-medium text-xs text-slate-900 dark:text-slate-200 font-sans">{{ subtask.title }}</span>
                <div class="flex items-center gap-1.5 shrink-0 font-mono text-[11px]">
                  <span v-if="subtask.complexity" class="px-1.5 py-0.2 rounded bg-slate-200 dark:bg-slate-800 text-slate-700 dark:text-slate-400 font-medium">
                    [{{ subtask.complexity }}]
                  </span>
                  <span class="px-1.5 py-0.2 rounded border bg-white dark:bg-slate-900 text-slate-700 dark:text-slate-300 border-slate-200 dark:border-slate-700">
                    {{ subtask.priority }}
                  </span>
                </div>
              </div>
              <p class="text-[11px] text-slate-600 dark:text-slate-400 leading-normal">{{ subtask.description }}</p>
              <div v-if="subtask.dependsOnTitles && subtask.dependsOnTitles.length > 0" class="text-[11px] text-indigo-600 dark:text-indigo-400 font-mono flex items-center gap-1">
                <ArrowRight class="w-3 h-3" />
                <span>Depends on: {{ subtask.dependsOnTitles.join(', ') }}</span>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- Footer -->
      <div v-if="result" class="pt-4 border-t border-slate-200 dark:border-slate-800 flex items-center justify-end gap-2">
        <button
          type="button"
          class="px-4 py-2 rounded-lg bg-slate-100 dark:bg-slate-900 hover:bg-slate-200 dark:hover:bg-slate-800 text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-slate-200 font-mono text-xs cursor-pointer min-h-[40px]"
          @click="emit('close')"
        >
          Dismiss
        </button>
        <button
          type="button"
          class="px-5 py-2 rounded-lg bg-indigo-600 hover:bg-indigo-500 text-white font-mono font-medium text-xs flex items-center gap-1.5 cursor-pointer shadow-xs min-h-[40px] disabled:opacity-50"
          :disabled="isInserted"
          @click="handleAcceptAll"
        >
          <Check v-if="isInserted" class="w-4 h-4 text-emerald-300" />
          <Plus v-else class="w-4 h-4 stroke-[2.5]" />
          <span>{{ isInserted ? 'Inserted into Board!' : `Add ${result.subtasks.length} Subtasks to Board` }}</span>
        </button>
      </div>
    </div>
  </div>
</template>

// src/components/AIDecomposerModal.svelte
<script lang="ts">
  import { decomposeGoalDeterministically } from '../lib/aiDecomposer';
  import { taskStore } from '../stores/taskStore.svelte';
  import type { DecomposedTaskResult, Task } from '../types/task';
  import { Sparkles, X, Check, ArrowRight, Layers, ShieldCheck } from 'lucide-svelte';

  interface Props {
    onClose: () => void;
  }

  let { onClose }: Props = $props();

  let goalInput = $state('');
  let result = $state<DecomposedTaskResult | null>(null);
  let isProcessing = $state(false);

  function handleDecompose() {
    if (!goalInput.trim()) return;
    isProcessing = true;
    setTimeout(() => {
      result = decomposeGoalDeterministically(goalInput);
      isProcessing = false;
    }, 120);
  }

  function handleCommitAll() {
    if (!result) return;
    const now = Date.now();
    const createdTasks: Task[] = [];
    const titleToIdMap = new Map<string, string>();

    result.subtasks.forEach((st, idx) => {
      const id = `TSK-${taskStore.tasks.length + 101 + idx}`;
      titleToIdMap.set(st.title, id);
    });

    result.subtasks.forEach((st, idx) => {
      const id = `TSK-${taskStore.tasks.length + 101 + idx}`;
      const deps: string[] = [];
      if (st.dependsOnTitles) {
        for (const depTitle of st.dependsOnTitles) {
          const depId = titleToIdMap.get(depTitle);
          if (depId) deps.push(depId);
        }
      }

      createdTasks.push({
        id,
        title: st.title,
        description: st.description,
        status: 'TODO',
        priority: st.priority,
        complexity: st.complexity,
        acceptanceCriteria: st.acceptanceCriteria,
        dependencies: deps,
        createdAt: now + idx * 10,
        updatedAt: now + idx * 10,
      });
    });

    taskStore.addBatchTasks(createdTasks);
    onClose();
  }
</script>

<svelte:window onkeydown={(e) => e.key === 'Escape' && onClose()} />

<!-- Modal Backdrop -->
<div class="fixed inset-0 z-50 bg-black/70 backdrop-blur-sm flex items-center justify-center p-3 md:p-6 animate-in fade-in duration-100">
  <div class="glass-panel glass-panel-glow w-full max-w-2xl rounded-2xl p-5 md:p-6 shadow-2xl border border-zinc-700/60 text-zinc-100 flex flex-col max-h-[90vh] overflow-hidden">
    <!-- Header -->
    <div class="flex items-center justify-between pb-4 border-b border-zinc-800">
      <div class="flex items-center gap-2.5">
        <div class="p-2 rounded-xl bg-indigo-500/10 border border-indigo-500/30 text-indigo-400">
          <Sparkles class="w-5 h-5" />
        </div>
        <div>
          <h2 class="text-base font-bold text-zinc-100">Deterministic AI Task Decomposer</h2>
          <p class="text-xs text-zinc-400">JSON-schema enforced goal breakdown with dependencies and acceptance criteria</p>
        </div>
      </div>
      <button
        class="p-2 hover:bg-zinc-800 rounded-lg text-zinc-400 hover:text-zinc-200 cursor-pointer min-h-[40px]"
        onclick={onClose}
      >
        <X class="w-5 h-5" />
      </button>
    </div>

    <!-- Body -->
    <div class="flex-1 overflow-y-auto py-4 space-y-4">
      <div>
        <label for="goal-input" class="block text-xs font-mono font-medium text-zinc-300 mb-1.5">
          Engineering Goal or Feature Specification:
        </label>
        <div class="flex gap-2">
          <input
            id="goal-input"
            type="text"
            bind:value={goalInput}
            placeholder="e.g., Implement biometric WebAuthn auth flow with fallback"
            class="flex-1 bg-zinc-900/90 border border-zinc-700 rounded-xl px-3.5 py-2.5 text-sm text-zinc-100 placeholder-zinc-500 focus:outline-none focus:border-indigo-500 font-sans min-h-[44px]"
            onkeydown={(e) => e.key === 'Enter' && handleDecompose()}
            autofocus
          />
          <button
            class="px-4 py-2.5 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-semibold cursor-pointer transition disabled:opacity-50 min-h-[44px]"
            onclick={handleDecompose}
            disabled={!goalInput.trim() || isProcessing}
          >
            {isProcessing ? 'Compiling...' : 'Decompose'}
          </button>
        </div>
      </div>

      {#if result}
        <div class="space-y-3 pt-2">
          <div class="p-3 rounded-xl bg-indigo-950/20 border border-indigo-500/20 flex items-start gap-2.5">
            <ShieldCheck class="w-4 h-4 text-indigo-400 shrink-0 mt-0.5" />
            <p class="text-xs text-indigo-200/90 leading-relaxed">{result.rationale}</p>
          </div>

          <div class="space-y-2.5">
            <div class="text-[11px] font-mono uppercase text-zinc-400 tracking-wider">
              Generated Subtask DAG ({result.subtasks.length} items):
            </div>
            {#each result.subtasks as st, idx}
              <div class="p-3 rounded-xl bg-zinc-900/60 border border-zinc-800 flex flex-col gap-1.5">
                <div class="flex items-center justify-between">
                  <span class="text-xs font-semibold text-zinc-200">{idx + 1}. {st.title}</span>
                  <div class="flex items-center gap-1.5">
                    <span class="px-2 py-0.5 rounded bg-zinc-800 border border-zinc-700 font-mono text-[10px] text-zinc-300">
                      {st.complexity}
                    </span>
                    <span class="px-2 py-0.5 rounded font-mono text-[10px] {st.priority === 'CRITICAL' ? 'bg-red-500/20 text-red-300' : 'bg-blue-500/20 text-blue-300'}">
                      {st.priority}
                    </span>
                  </div>
                </div>
                <p class="text-xs text-zinc-400">{st.description}</p>
                {#if st.acceptanceCriteria.length > 0}
                  <div class="mt-1 pt-1.5 border-t border-zinc-800/80 text-[11px] text-zinc-400 space-y-0.5">
                    <span class="font-mono text-[10px] text-zinc-400 font-medium">Acceptance Criteria:</span>
                    <ul class="list-disc list-inside space-y-0.5 text-zinc-300">
                      {#each st.acceptanceCriteria as ac}
                        <li>{ac}</li>
                      {/each}
                    </ul>
                  </div>
                {/if}
              </div>
            {/each}
          </div>
        </div>
      {/if}
    </div>

    <!-- Footer -->
    <div class="pt-4 border-t border-zinc-800 flex items-center justify-between">
      <span class="text-xs text-zinc-400 font-mono">Zero hallucination / schema-validated</span>
      <div class="flex items-center gap-2">
        <button
          class="px-3.5 py-2 rounded-xl bg-zinc-800 hover:bg-zinc-700 text-zinc-300 text-xs font-medium cursor-pointer min-h-[44px]"
          onclick={onClose}
        >
          Cancel
        </button>
        {#if result}
          <button
            class="px-4 py-2 rounded-xl bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-semibold cursor-pointer transition shadow-lg shadow-emerald-600/20 flex items-center gap-1.5 min-h-[44px]"
            onclick={handleCommitAll}
          >
            <Check class="w-4 h-4" />
            <span>Commit to Backlog</span>
          </button>
        {/if}
      </div>
    </div>
  </div>
</div>
