// source/frontend/components/KanbanBoard.vue
<script setup lang="ts">
import { useTaskStore } from '../stores/taskStore';
import type { Task, TaskPriority, TaskStatus } from '../types/task';
import { Flame, Clock, Plus, ChevronLeft, ChevronRight, AlertCircle } from 'lucide-vue-next';

defineProps<{
  onOpenCreate: () => void;
}>();

const taskStore = useTaskStore();

const COLUMNS: { status: TaskStatus; label: string; dotClass: string; borderClass: string; badgeClass: string }[] = [
  {
    status: 'TODO',
    label: 'To Do',
    dotClass: 'bg-slate-400 dark:bg-slate-500',
    borderClass: 'border-slate-300 dark:border-slate-800',
    badgeClass: 'text-slate-700 bg-slate-200 border-slate-300 dark:text-slate-400 dark:bg-slate-900 dark:border-slate-800',
  },
  {
    status: 'IN_PROGRESS',
    label: 'In Progress',
    dotClass: 'bg-sky-500',
    borderClass: 'border-sky-200 dark:border-sky-950/60',
    badgeClass: 'text-sky-700 bg-sky-100 border-sky-200 dark:text-sky-300 dark:bg-sky-950/40 dark:border-sky-800/60',
  },
  {
    status: 'BLOCKED',
    label: 'Blocked',
    dotClass: 'bg-rose-500',
    borderClass: 'border-rose-200 dark:border-rose-950/60',
    badgeClass: 'text-rose-700 bg-rose-100 border-rose-200 dark:text-rose-300 dark:bg-rose-950/40 dark:border-rose-800/60',
  },
  {
    status: 'DONE',
    label: 'Done',
    dotClass: 'bg-emerald-500',
    borderClass: 'border-emerald-200 dark:border-emerald-950/60',
    badgeClass: 'text-emerald-700 bg-emerald-100 border-emerald-200 dark:text-emerald-300 dark:bg-emerald-950/40 dark:border-emerald-800/60',
  },
];

function getPriorityBadge(p: TaskPriority) {
  switch (p) {
    case 'CRITICAL':
      return 'bg-rose-100 text-rose-800 border-rose-300 dark:bg-rose-950/60 dark:text-rose-300 dark:border-rose-800/80 font-bold';
    case 'HIGH':
      return 'bg-amber-100 text-amber-800 border-amber-300 dark:bg-amber-950/50 dark:text-amber-300 dark:border-amber-800/60 font-semibold';
    case 'MEDIUM':
      return 'bg-blue-100 text-blue-800 border-blue-300 dark:bg-blue-950/40 dark:text-blue-300 dark:border-blue-800/40 font-medium';
    case 'LOW':
    default:
      return 'bg-slate-100 text-slate-700 border-slate-300 dark:bg-slate-900 dark:text-slate-400 dark:border-slate-800 font-medium';
  }
}

function moveStatus(task: Task, direction: 'left' | 'right') {
  const statuses: TaskStatus[] = ['TODO', 'IN_PROGRESS', 'BLOCKED', 'DONE'];
  const currentIndex = statuses.indexOf(task.status);
  let nextIndex: number;
  if (direction === 'right') {
    nextIndex = (currentIndex + 1) % statuses.length;
  } else {
    nextIndex = (currentIndex - 1 + statuses.length) % statuses.length;
  }
  taskStore.setStatus(task.id, statuses[nextIndex]);
  taskStore.syncKanbanFocusToTask(task.id);
}

function handleDragStart(e: DragEvent, taskId: string) {
  if (e.dataTransfer) {
    e.dataTransfer.setData('text/plain', taskId);
    e.dataTransfer.effectAllowed = 'move';
  }
}

function handleDragOver(e: DragEvent) {
  e.preventDefault();
  if (e.dataTransfer) {
    e.dataTransfer.dropEffect = 'move';
  }
}

function handleDrop(e: DragEvent, targetStatus: TaskStatus, colIndex: number) {
  e.preventDefault();
  if (e.dataTransfer) {
    const taskId = e.dataTransfer.getData('text/plain');
    if (taskId) {
      taskStore.setStatus(taskId, targetStatus);
      taskStore.syncKanbanFocusToTask(taskId);
    }
  }
}

function selectCard(task: Task, colIndex: number, rowIndex: number) {
  taskStore.kanbanColIndex = colIndex;
  taskStore.kanbanRowIndex = rowIndex;
}
</script>

<template>
  <div class="h-full grid grid-cols-1 md:grid-cols-4 gap-4 items-start">
    <div
      v-for="(col, colIndex) in COLUMNS"
      :key="col.status"
      class="flex flex-col h-full max-h-full bg-slate-200/60 dark:bg-slate-900/80 border rounded-lg p-3 shadow-2xs"
      :class="taskStore.kanbanColIndex === colIndex ? 'border-slate-400 dark:border-slate-700' : 'border-slate-300 dark:border-slate-800'"
      @dragover="handleDragOver"
      @drop="(e) => handleDrop(e, col.status, colIndex)"
      role="region"
      :aria-label="`${col.label} column`"
      :data-column="col.status"
    >
      <!-- Column Header -->
      <div class="shrink-0 pb-2.5 border-b border-slate-300 dark:border-slate-800 flex items-center justify-between select-none">
        <div class="flex items-center gap-2">
          <span class="w-2.5 h-2.5 rounded-full" :class="col.dotClass"></span>
          <h3 class="text-xs md:text-sm font-mono font-bold text-slate-800 dark:text-slate-200">{{ col.label }}</h3>
        </div>
        <span class="h-6 px-2 inline-flex items-center justify-center rounded-md text-[11px] font-mono border font-semibold" :class="col.badgeClass">
          {{ taskStore.filteredTasks.filter((t) => t.status === col.status).length }}
        </span>
      </div>

      <!-- Cards Container (Clustered Naturally) -->
      <div class="flex-1 min-h-0 overflow-y-auto space-y-2.5 py-2.5 pr-1 no-scrollbar">
        <div
          v-if="taskStore.filteredTasks.filter((t) => t.status === col.status).length === 0"
          class="text-center py-6 text-xs text-slate-400 dark:text-slate-600 font-mono"
        >
          Empty column
        </div>

        <div
          v-for="(task, rowIndex) in taskStore.filteredTasks.filter((t) => t.status === col.status)"
          :key="task.id"
          class="group rounded-md p-3 shadow-xs cursor-grab active:cursor-grabbing select-none border"
          :class="taskStore.activeKanbanTask?.id === task.id
            ? 'ring-2 ring-inset ring-indigo-500 dark:ring-indigo-400 border-indigo-500 dark:border-indigo-400 bg-slate-50 dark:bg-slate-800/90 shadow-sm'
            : 'border-slate-300 dark:border-slate-700/80 bg-white dark:bg-slate-900 hover:border-slate-400 dark:hover:border-slate-600 hover:bg-slate-50 dark:hover:bg-slate-800'"
          draggable="true"
          @dragstart="(e) => handleDragStart(e, task.id)"
          @click="selectCard(task, colIndex, rowIndex)"
          @dblclick="taskStore.openDetail(task.id)"
          role="article"
          :data-task="task.id"
          :data-active-card="taskStore.activeKanbanTask?.id === task.id"
        >
          <!-- Top Row: ID & Badges -->
          <div class="flex items-center justify-between gap-1 mb-1.5 text-xs font-mono">
            <span class="text-slate-500 dark:text-slate-400 font-semibold">{{ task.id }}</span>
            <div class="flex items-center gap-1.5">
              <span v-if="taskStore.criticalPathIds.has(task.id) && task.status !== 'DONE'" title="Critical Path" class="text-rose-600 dark:text-rose-400">
                <Flame class="w-3.5 h-3.5" />
              </span>
              <span class="h-5 px-1.5 inline-flex items-center justify-center rounded-md border text-[11px] uppercase font-bold" :class="getPriorityBadge(task.priority)">
                {{ task.priority.slice(0, 4) }}
              </span>
            </div>
          </div>

          <!-- Title -->
          <h4 class="text-sm font-medium font-sans text-slate-900 dark:text-slate-100 mb-2 leading-snug" :class="task.status === 'DONE' ? 'line-through text-slate-400 dark:text-slate-500 font-normal' : ''">
            {{ task.title }}
          </h4>

          <!-- Blocking Reason -->
          <div v-if="task.blockingReason && task.status === 'BLOCKED'" class="flex items-center gap-1.5 text-xs text-rose-700 dark:text-rose-400/90 font-mono mb-2 bg-rose-50 dark:bg-rose-950/30 p-1.5 rounded-md border border-rose-200 dark:border-rose-900/40">
            <AlertCircle class="w-3.5 h-3.5 shrink-0" />
            <span class="truncate">{{ task.blockingReason }}</span>
          </div>

          <!-- Footer Row -->
          <div class="flex items-center justify-between text-xs font-mono text-slate-500 dark:text-slate-400 pt-2 border-t border-slate-100 dark:border-slate-800">
            <div class="flex items-center gap-1">
              <Clock v-if="task.dueDate" class="w-3.5 h-3.5 text-slate-400 dark:text-slate-500" />
              <span v-if="task.dueDate">{{ new Date(task.dueDate).toLocaleDateString(undefined, { month: 'short', day: 'numeric' }) }}</span>
              <span v-else>-</span>
            </div>

            <!-- Quick Column Shift Controls -->
            <div class="flex items-center gap-1 opacity-60 group-hover:opacity-100">
              <button
                type="button"
                class="p-1 hover:bg-slate-200 dark:hover:bg-slate-700 rounded-md text-slate-500 dark:text-slate-400 hover:text-slate-800 dark:hover:text-slate-200 cursor-pointer"
                @click.stop="moveStatus(task, 'left')"
                title="Move left (H)"
              >
                <ChevronLeft class="w-3.5 h-3.5" />
              </button>
              <button
                type="button"
                class="p-1 hover:bg-slate-200 dark:hover:bg-slate-700 rounded-md text-slate-500 dark:text-slate-400 hover:text-slate-800 dark:hover:text-slate-200 cursor-pointer"
                @click.stop="moveStatus(task, 'right')"
                title="Move right (L)"
              >
                <ChevronRight class="w-3.5 h-3.5" />
              </button>
            </div>
          </div>
        </div>
      </div>

      <!-- Quick Add Button: h-8 rounded-md standard -->
      <button
        type="button"
        class="h-8 w-full mt-2 border border-dashed border-slate-300 dark:border-slate-700 rounded-md hover:bg-white dark:hover:bg-slate-800 text-xs font-mono flex items-center justify-center gap-1.5 text-slate-600 dark:text-slate-300 hover:text-slate-900 dark:hover:text-white cursor-pointer shrink-0"
        @click="onOpenCreate"
      >
        <Plus class="w-3.5 h-3.5" />
        <span>New Task</span>
      </button>
    </div>
  </div>
</template>

// src/components/KanbanBoard.svelte
<script lang="ts">
  import { taskStore } from '../stores/taskStore.svelte';
  import type { Task, TaskStatus, TaskPriority } from '../types/task';
  import { Flame, Plus, ChevronLeft, ChevronRight, Clock, AlertCircle } from 'lucide-svelte';

  interface Props {
    onOpenCreate: () => void;
  }

  let { onOpenCreate }: Props = $props();

  const COLUMNS: { status: TaskStatus; label: string; dotClass: string; borderClass: string; badgeClass: string }[] = [
    { status: 'TODO', label: 'To Do', dotClass: 'bg-zinc-500', borderClass: 'border-zinc-800', badgeClass: 'text-zinc-400 bg-zinc-900 border-zinc-800' },
    { status: 'IN_PROGRESS', label: 'In Progress', dotClass: 'bg-sky-400 shadow-[0_0_8px_rgba(56,189,248,0.4)]', borderClass: 'border-sky-950/60', badgeClass: 'text-sky-300 bg-sky-950/40 border-sky-800/60' },
    { status: 'BLOCKED', label: 'Blocked', dotClass: 'bg-rose-400 shadow-[0_0_8px_rgba(251,113,133,0.4)]', borderClass: 'border-rose-950/60', badgeClass: 'text-rose-300 bg-rose-950/40 border-rose-800/60' },
    { status: 'DONE', label: 'Completed', dotClass: 'bg-emerald-400 shadow-[0_0_8px_rgba(52,211,153,0.4)]', borderClass: 'border-emerald-950/60', badgeClass: 'text-emerald-300 bg-emerald-950/40 border-emerald-800/60' },
  ];

  function getPriorityBadge(p: TaskPriority) {
    switch (p) {
      case 'CRITICAL':
        return 'bg-rose-950/60 text-rose-300 border-rose-800/80 font-bold';
      case 'HIGH':
        return 'bg-amber-950/50 text-amber-300 border-amber-800/60 font-semibold';
      case 'MEDIUM':
        return 'bg-blue-950/40 text-blue-300 border-blue-800/40';
      case 'LOW':
      default:
        return 'bg-zinc-900 text-zinc-400 border-zinc-800';
    }
  }

  function moveStatus(task: Task, direction: 'left' | 'right') {
    const order: TaskStatus[] = ['TODO', 'IN_PROGRESS', 'BLOCKED', 'DONE'];
    const currIdx = order.indexOf(task.status);
    if (direction === 'left' && currIdx > 0) {
      taskStore.setStatus(task.id, order[currIdx - 1]);
    } else if (direction === 'right' && currIdx < order.length - 1) {
      taskStore.setStatus(task.id, order[currIdx + 1]);
    }
  }

  // HTML5 Drag and Drop handlers
  function handleDragStart(e: DragEvent, taskId: string) {
    if (e.dataTransfer) {
      e.dataTransfer.setData('text/plain', taskId);
      e.dataTransfer.effectAllowed = 'move';
    }
  }

  function handleDragOver(e: DragEvent) {
    e.preventDefault();
    if (e.dataTransfer) {
      e.dataTransfer.dropEffect = 'move';
    }
  }

  function handleDrop(e: DragEvent, targetStatus: TaskStatus) {
    e.preventDefault();
    if (e.dataTransfer) {
      const taskId = e.dataTransfer.getData('text/plain');
      if (taskId) {
        taskStore.setStatus(taskId, targetStatus);
      }
    }
  }
</script>

<div class="w-full flex-1 p-3 md:p-4 overflow-x-auto">
  <div class="grid grid-cols-1 md:grid-cols-4 gap-3 md:gap-4 min-w-[300px] md:min-w-[900px] h-full items-start">
    {#each COLUMNS as col}
      {@const colTasks = taskStore.filteredTasks.filter((t) => t.status === col.status)}
      <div
        class="flex flex-col bg-zinc-950/50 border {col.borderClass} rounded-xl p-3 max-h-[calc(100vh-140px)] min-h-[300px]"
        ondragover={handleDragOver}
        ondrop={(e) => handleDrop(e, col.status)}
        role="region"
        aria-label="{col.label} column"
      >
        <!-- Column Header -->
        <div class="flex items-center justify-between pb-2 mb-2 border-b border-zinc-800/80 select-none">
          <div class="flex items-center gap-2">
            <span class="w-2 h-2 rounded-full {col.dotClass}"></span>
            <h3 class="text-xs font-mono font-bold text-zinc-200">{col.label}</h3>
          </div>
          <span class="px-2 py-0.5 rounded text-[10px] font-mono border {col.badgeClass}">
            {colTasks.length}
          </span>
        </div>

        <!-- Cards List -->
        <div class="flex-1 overflow-y-auto space-y-2 pr-1 no-scrollbar">
          {#if colTasks.length === 0}
            <div class="text-center py-8 text-[11px] text-zinc-600 font-mono">
              Empty column
            </div>
          {:else}
            {#each colTasks as task (task.id)}
              {@const isCritical = taskStore.criticalPathIds.has(task.id)}
              <div
                class="group bg-zinc-900/90 hover:bg-zinc-900 border border-zinc-800/80 hover:border-zinc-700 rounded-lg p-2.5 transition shadow-sm cursor-grab active:cursor-grabbing select-none"
                draggable="true"
                ondragstart={(e) => handleDragStart(e, task.id)}
                role="article"
              >
                <!-- Top Row: ID & Badges -->
                <div class="flex items-center justify-between gap-1 mb-1.5 text-[10px] font-mono">
                  <span class="text-zinc-500 font-medium">{task.id}</span>
                  <div class="flex items-center gap-1">
                    {#if isCritical && task.status !== 'DONE'}
                      <span title="Critical Path" class="text-rose-400">
                        <Flame class="w-3.5 h-3.5" />
                      </span>
                    {/if}
                    <span class="px-1.5 py-0.2 rounded border {getPriorityBadge(task.priority)}">
                      {task.priority.slice(0, 4)}
                    </span>
                  </div>
                </div>

                <!-- Title -->
                <h4 class="text-xs font-normal text-zinc-200 mb-1.5 leading-snug {task.status === 'DONE' ? 'line-through text-zinc-500' : ''}">
                  {task.title}
                </h4>

                <!-- Blocking Reason Warning -->
                {#if task.blocking_reason && task.status === 'BLOCKED'}
                  <div class="flex items-center gap-1 text-[10px] text-rose-400/90 font-mono mb-1.5 bg-rose-950/30 p-1 rounded border border-rose-900/40">
                    <AlertCircle class="w-3 h-3 shrink-0" />
                    <span class="truncate">{task.blocking_reason}</span>
                  </div>
                {/if}

                <!-- Footer Row: Due Date & Shift Controls -->
                <div class="flex items-center justify-between text-[10px] font-mono text-zinc-500 pt-1.5 border-t border-zinc-850">
                  <div class="flex items-center gap-1">
                    {#if task.dueDate}
                      <Clock class="w-3 h-3 text-zinc-500" />
                      <span>{new Date(task.dueDate).toLocaleDateString(undefined, { month: 'short', day: 'numeric' })}</span>
                    {:else}
                      <span>-</span>
                    {/if}
                  </div>

                  <!-- Quick Column Shift Controls -->
                  <div class="flex items-center gap-0.5 opacity-60 group-hover:opacity-100 transition">
                    {#if col.status !== 'TODO'}
                      <button
                        type="button"
                        class="p-0.5 hover:bg-zinc-800 rounded text-zinc-400 hover:text-zinc-200 cursor-pointer"
                        onclick={() => moveStatus(task, 'left')}
                        title="Move left"
                      >
                        <ChevronLeft class="w-3.5 h-3.5" />
                      </button>
                    {/if}
                    {#if col.status !== 'DONE'}
                      <button
                        type="button"
                        class="p-0.5 hover:bg-zinc-800 rounded text-zinc-400 hover:text-zinc-200 cursor-pointer"
                        onclick={() => moveStatus(task, 'right')}
                        title="Move right"
                      >
                        <ChevronRight class="w-3.5 h-3.5" />
                      </button>
                    {/if}
                  </div>
                </div>
              </div>
            {/each}
          {/if}
        </div>

        <!-- Add Task Quick Button at Column Bottom -->
        <button
          type="button"
          class="w-full mt-2 py-1.5 rounded-lg border border-dashed border-zinc-800 hover:border-zinc-700 hover:bg-zinc-900/40 text-zinc-500 hover:text-zinc-300 text-xs font-mono flex items-center justify-center gap-1 cursor-pointer transition"
          onclick={onOpenCreate}
        >
          <Plus class="w-3.5 h-3.5" />
          <span>New Task</span>
        </button>
      </div>
    {/each}
  </div>
</div>
