// src/components/ShortcutsHelpModal.svelte
<script lang="ts">
  import { Keyboard, X, Smartphone, MousePointer } from 'lucide-svelte';

  interface Props {
    onClose: () => void;
  }

  let { onClose }: Props = $props();
</script>

<svelte:window onkeydown={(e) => e.key === 'Escape' && onClose()} />

<div class="fixed inset-0 z-50 bg-black/70 backdrop-blur-sm flex items-center justify-center p-3 md:p-6 animate-in fade-in duration-100">
  <div class="glass-panel glass-panel-glow w-full max-w-2xl rounded-2xl p-5 md:p-6 shadow-2xl border border-zinc-700/60 text-zinc-100 flex flex-col max-h-[90vh] overflow-hidden">
    <!-- Header -->
    <div class="flex items-center justify-between pb-4 border-b border-zinc-800">
      <div class="flex items-center gap-2.5">
        <div class="p-2 rounded-xl bg-zinc-800 border border-zinc-700 text-zinc-200">
          <Keyboard class="w-5 h-5" />
        </div>
        <div>
          <h2 class="text-base font-bold text-zinc-100">Keyboard & Touch Ergonomics Guide</h2>
          <p class="text-xs text-zinc-400">Modal-less Vim velocity & mobile swipe gestures</p>
        </div>
      </div>
      <button class="p-2 hover:bg-zinc-800 rounded-lg text-zinc-400 hover:text-zinc-200 cursor-pointer min-h-[40px]" onclick={onClose}>
        <X class="w-5 h-5" />
      </button>
    </div>

    <!-- Body -->
    <div class="flex-1 overflow-y-auto py-4 space-y-5 text-xs">
      <!-- Vim Shortcuts -->
      <div>
        <div class="flex items-center gap-2 font-mono uppercase text-indigo-400 font-semibold mb-2.5 text-[11px] tracking-wider">
          <Keyboard class="w-4 h-4" />
          <span>Vim / Linear Keyboard Navigation</span>
        </div>
        <div class="grid grid-cols-1 md:grid-cols-2 gap-2">
          <div class="p-2.5 rounded-xl bg-zinc-900/60 border border-zinc-800 flex items-center justify-between">
            <span class="text-zinc-300">Navigate down / up</span>
            <div class="flex gap-1">
              <kbd class="px-2 py-1 rounded bg-zinc-800 border border-zinc-700 font-mono text-[11px]">j</kbd>
              <kbd class="px-2 py-1 rounded bg-zinc-800 border border-zinc-700 font-mono text-[11px]">k</kbd>
            </div>
          </div>
          <div class="p-2.5 rounded-xl bg-zinc-900/60 border border-zinc-800 flex items-center justify-between">
            <span class="text-zinc-300">Cycle status</span>
            <kbd class="px-2 py-1 rounded bg-zinc-800 border border-zinc-700 font-mono text-[11px]">Space</kbd>
          </div>
          <div class="p-2.5 rounded-xl bg-zinc-900/60 border border-zinc-800 flex items-center justify-between">
            <span class="text-zinc-300">Inline rename title</span>
            <kbd class="px-2 py-1 rounded bg-zinc-800 border border-zinc-700 font-mono text-[11px]">Enter</kbd>
          </div>
          <div class="p-2.5 rounded-xl bg-zinc-900/60 border border-zinc-800 flex items-center justify-between">
            <span class="text-zinc-300">Create new task</span>
            <kbd class="px-2 py-1 rounded bg-zinc-800 border border-zinc-700 font-mono text-[11px]">c</kbd>
          </div>
          <div class="p-2.5 rounded-xl bg-zinc-900/60 border border-zinc-800 flex items-center justify-between">
            <span class="text-zinc-300">Delete selected task</span>
            <kbd class="px-2 py-1 rounded bg-zinc-800 border border-zinc-700 font-mono text-[11px]">d</kbd>
          </div>
          <div class="p-2.5 rounded-xl bg-zinc-900/60 border border-zinc-800 flex items-center justify-between">
            <span class="text-zinc-300">Focus search filter</span>
            <kbd class="px-2 py-1 rounded bg-zinc-800 border border-zinc-700 font-mono text-[11px]">/</kbd>
          </div>
          <div class="p-2.5 rounded-xl bg-zinc-900/60 border border-zinc-800 flex items-center justify-between">
            <span class="text-zinc-300">Set Priority (Low..Crit)</span>
            <div class="flex gap-1">
              <kbd class="px-1.5 py-0.5 rounded bg-zinc-800 border border-zinc-700 font-mono text-[10px]">1</kbd>
              <kbd class="px-1.5 py-0.5 rounded bg-zinc-800 border border-zinc-700 font-mono text-[10px]">2</kbd>
              <kbd class="px-1.5 py-0.5 rounded bg-zinc-800 border border-zinc-700 font-mono text-[10px]">3</kbd>
              <kbd class="px-1.5 py-0.5 rounded bg-zinc-800 border border-zinc-700 font-mono text-[10px]">4</kbd>
            </div>
          </div>
          <div class="p-2.5 rounded-xl bg-zinc-900/60 border border-zinc-800 flex items-center justify-between">
            <span class="text-zinc-300">AI Decomposer / Git Diff</span>
            <div class="flex gap-1">
              <kbd class="px-1.5 py-0.5 rounded bg-zinc-800 border border-zinc-700 font-mono text-[10px]">a</kbd>
              <kbd class="px-1.5 py-0.5 rounded bg-zinc-800 border border-zinc-700 font-mono text-[10px]">g</kbd>
            </div>
          </div>
        </div>
      </div>

      <!-- Mobile & Pointer -->
      <div>
        <div class="flex items-center gap-2 font-mono uppercase text-emerald-400 font-semibold mb-2.5 text-[11px] tracking-wider">
          <Smartphone class="w-4 h-4" />
          <span>Mobile Touch & Desktop Pointer Ergonomics</span>
        </div>
        <div class="grid grid-cols-1 md:grid-cols-2 gap-2">
          <div class="p-2.5 rounded-xl bg-zinc-900/60 border border-zinc-800 space-y-1">
            <div class="font-semibold text-zinc-200">Swipe Right (> 80px)</div>
            <p class="text-zinc-400">Instantly marks task as <span class="text-emerald-400">DONE</span> with optimistic updates.</p>
          </div>
          <div class="p-2.5 rounded-xl bg-zinc-900/60 border border-zinc-800 space-y-1">
            <div class="font-semibold text-zinc-200">Swipe Left (> 80px)</div>
            <p class="text-zinc-400">Toggles <span class="text-amber-400">BLOCKED</span> state or quick delete.</p>
          </div>
          <div class="p-2.5 rounded-xl bg-zinc-900/60 border border-zinc-800 space-y-1">
            <div class="font-semibold text-zinc-200">Double Click Title</div>
            <p class="text-zinc-400">Enters inline non-blocking text editing mode.</p>
          </div>
          <div class="p-2.5 rounded-xl bg-zinc-900/60 border border-zinc-800 space-y-1">
            <div class="font-semibold text-zinc-200">Right Click (Context Menu)</div>
            <p class="text-zinc-400">1-click direct menu for status & priority changes without opening dialogs.</p>
          </div>
        </div>
      </div>
    </div>

    <!-- Footer -->
    <div class="pt-4 border-t border-zinc-800 flex justify-end">
      <button class="px-4 py-2 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-semibold cursor-pointer min-h-[44px]" onclick={onClose}>
        Got It
      </button>
    </div>
  </div>
</div>

// src/components/ShortcutsHelpModal.vue
<script setup lang="ts">
import { Keyboard, X } from 'lucide-vue-next';

const emit = defineEmits<{
  (e: 'close'): void;
}>();

const SHORTCUTS = [
  { key: 'b', desc: 'Toggle Table / Kanban View' },
  { key: 'h / j / k / l', desc: 'Vim Spatial Navigation (2D Kanban / Table Rows)' },
  { key: 'H / L', desc: 'Shift Selected Task Left / Right across Columns' },
  { key: 'Space', desc: 'Cycle Task Status (TODO → IN_PROGRESS → BLOCKED → DONE)' },
  { key: 'Enter', desc: 'Inline Rename / Title Edit' },
  { key: 'd / Backspace', desc: 'Delete Selected Task' },
  { key: '1, 2, 3, 4', desc: 'Set Priority (LOW, MEDIUM, HIGH, CRITICAL)' },
  { key: 'c', desc: 'Open Task Creation Dialog' },
  { key: '/', desc: 'Quick Filter / Search' },
  { key: 'a', desc: 'Open Task Decomposer' },
  { key: 'g', desc: 'Open Git Diff Parser' },
  { key: 'v', desc: 'Open DAG Visualizer & Critical Path' },
  { key: 't', desc: 'Toggle Light / Dark Theme Mode' },
  { key: '?', desc: 'Show Keyboard Shortcuts' },
  { key: 'Esc', desc: 'Exit editing / Dismiss dialogs' },
];
</script>

<template>
  <div
    class="fixed inset-0 z-50 bg-slate-900/40 dark:bg-black/75 backdrop-blur-xs flex items-center justify-center p-3 md:p-6 animate-in fade-in duration-100"
    @click.self="emit('close')"
  >
    <div class="bg-white dark:bg-slate-900 w-full max-w-lg rounded-lg p-5 md:p-6 shadow-2xl border border-slate-300 dark:border-slate-800 text-slate-900 dark:text-slate-100 flex flex-col">
      <!-- Header -->
      <div class="flex items-center justify-between pb-3 border-b border-slate-200 dark:border-slate-800">
        <div class="flex items-center gap-2.5">
          <div class="p-2 rounded-md bg-slate-100 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-slate-800 dark:text-slate-200">
            <Keyboard class="w-5 h-5" />
          </div>
          <div>
            <h2 class="text-sm md:text-base font-semibold text-slate-900 dark:text-slate-100 font-sans">Keyboard Shortcuts</h2>
            <p class="text-[11px] text-slate-500 dark:text-slate-400">Global hotkeys and quick actions</p>
          </div>
        </div>
        <button type="button" class="p-1.5 hover:bg-slate-100 dark:hover:bg-slate-800 rounded-md text-slate-400 hover:text-slate-600 dark:hover:text-slate-200 cursor-pointer" @click="emit('close')">
          <X class="w-5 h-5" />
        </button>
      </div>

      <!-- Content -->
      <div class="py-4 space-y-2 text-xs divide-y divide-slate-100 dark:divide-slate-800/60 max-h-[60vh] overflow-y-auto">
        <div
          v-for="s in SHORTCUTS"
          :key="s.key"
          class="pt-2 flex items-center justify-between font-mono"
        >
          <kbd class="h-6 px-2 inline-flex items-center justify-center rounded-md bg-slate-100 dark:bg-slate-900 border border-slate-300 dark:border-slate-700 text-slate-800 dark:text-slate-200 text-[11px] font-bold">
            {{ s.key }}
          </kbd>
          <span class="text-slate-600 dark:text-slate-400 font-sans text-xs">{{ s.desc }}</span>
        </div>
      </div>
    </div>
  </div>
</template>
