// src/components/TaskContextMenu.svelte
<script lang="ts">
  import type { Task, TaskPriority, TaskStatus } from '../types/task';
  import { taskStore } from '../stores/taskStore.svelte';
  import { CheckCircle2, CircleDot, AlertOctagon, CheckSquare, Trash2, Edit3, Flag } from 'lucide-svelte';

  interface Props {
    task: Task;
    x: number;
    y: number;
    onClose: () => void;
  }

  let { task, x, y, onClose }: Props = $props();

  function handleSetStatus(status: TaskStatus) {
    taskStore.setStatus(task.id, status);
    onClose();
  }

  function handleSetPriority(p: TaskPriority) {
    taskStore.setPriority(task.id, p);
    onClose();
  }

  function handleStartEdit() {
    taskStore.startEditing(task.id);
    onClose();
  }

  function handleDelete() {
    taskStore.deleteTask(task.id);
    onClose();
  }
</script>

<svelte:window onpointerdown={onClose} onkeydown={(e) => e.key === 'Escape' && onClose()} />

<!-- Context Menu Popup -->
<div
  class="fixed z-50 min-w-[200px] rounded-xl bg-zinc-900/95 p-1.5 shadow-2xl border border-zinc-700/60 backdrop-blur-xl text-xs text-zinc-200 animate-in fade-in zoom-in-95 duration-100"
  style="top: {Math.min(y, window.innerHeight - 300)}px; left: {Math.min(x, window.innerWidth - 220)}px;"
  role="menu"
  tabindex="-1"
  onpointerdown={(e) => e.stopPropagation()}
>
  <div class="px-2.5 py-1 text-[10px] font-mono font-semibold uppercase tracking-wider text-zinc-400 border-b border-zinc-800">
    {task.id} Actions
  </div>

  <!-- Status options -->
  <div class="py-1">
    <div class="px-2 py-0.5 text-[10px] text-zinc-400 uppercase tracking-wider">Set Status</div>
    <button
      class="w-full flex items-center gap-2 px-2.5 py-1.5 rounded-lg hover:bg-zinc-800 transition text-left cursor-pointer min-h-[36px]"
      onclick={() => handleSetStatus('TODO')}
    >
      <CircleDot class="w-3.5 h-3.5 text-zinc-400" />
      <span>TODO</span>
    </button>
    <button
      class="w-full flex items-center gap-2 px-2.5 py-1.5 rounded-lg hover:bg-zinc-800 transition text-left cursor-pointer min-h-[36px]"
      onclick={() => handleSetStatus('IN_PROGRESS')}
    >
      <CheckCircle2 class="w-3.5 h-3.5 text-blue-400" />
      <span>IN PROGRESS</span>
    </button>
    <button
      class="w-full flex items-center gap-2 px-2.5 py-1.5 rounded-lg hover:bg-zinc-800 transition text-left cursor-pointer min-h-[36px]"
      onclick={() => handleSetStatus('BLOCKED')}
    >
      <AlertOctagon class="w-3.5 h-3.5 text-amber-400" />
      <span>BLOCKED</span>
    </button>
    <button
      class="w-full flex items-center gap-2 px-2.5 py-1.5 rounded-lg hover:bg-zinc-800 transition text-left cursor-pointer min-h-[36px]"
      onclick={() => handleSetStatus('DONE')}
    >
      <CheckSquare class="w-3.5 h-3.5 text-emerald-400" />
      <span>DONE</span>
    </button>
  </div>

  <!-- Priority options -->
  <div class="border-t border-zinc-800/80 py-1">
    <div class="px-2 py-0.5 text-[10px] text-zinc-400 uppercase tracking-wider">Priority</div>
    <div class="grid grid-cols-2 gap-1 px-1">
      <button
        class="flex items-center gap-1.5 px-2 py-1 rounded bg-zinc-800/50 hover:bg-zinc-800 text-[11px] text-zinc-300 min-h-[32px]"
        onclick={() => handleSetPriority('LOW')}
      >
        <Flag class="w-3 h-3 text-zinc-400" />
        <span>Low</span>
      </button>
      <button
        class="flex items-center gap-1.5 px-2 py-1 rounded bg-zinc-800/50 hover:bg-zinc-800 text-[11px] text-blue-300 min-h-[32px]"
        onclick={() => handleSetPriority('MEDIUM')}
      >
        <Flag class="w-3 h-3 text-blue-400" />
        <span>Med</span>
      </button>
      <button
        class="flex items-center gap-1.5 px-2 py-1 rounded bg-zinc-800/50 hover:bg-zinc-800 text-[11px] text-amber-300 min-h-[32px]"
        onclick={() => handleSetPriority('HIGH')}
      >
        <Flag class="w-3 h-3 text-amber-400" />
        <span>High</span>
      </button>
      <button
        class="flex items-center gap-1.5 px-2 py-1 rounded bg-zinc-800/50 hover:bg-zinc-800 text-[11px] text-red-300 min-h-[32px]"
        onclick={() => handleSetPriority('CRITICAL')}
      >
        <Flag class="w-3 h-3 text-red-400 font-bold" />
        <span>Crit</span>
      </button>
    </div>
  </div>

  <!-- Mutate / Delete -->
  <div class="border-t border-zinc-800/80 pt-1">
    <button
      class="w-full flex items-center gap-2 px-2.5 py-1.5 rounded-lg hover:bg-zinc-800 text-zinc-200 transition text-left cursor-pointer min-h-[36px]"
      onclick={handleStartEdit}
    >
      <Edit3 class="w-3.5 h-3.5 text-zinc-400" />
      <span>Inline Rename (Enter)</span>
    </button>
    <button
      class="w-full flex items-center gap-2 px-2.5 py-1.5 rounded-lg hover:bg-red-950/40 text-red-400 hover:text-red-300 transition text-left cursor-pointer min-h-[36px]"
      onclick={handleDelete}
    >
      <Trash2 class="w-3.5 h-3.5" />
      <span>Delete Task (d)</span>
    </button>
  </div>
</div>

// src/components/TaskContextMenu.vue
<script setup lang="ts">
import { computed, onMounted, onUnmounted } from 'vue';
import { useTaskStore } from '../stores/taskStore';
import type { Task, TaskPriority, TaskStatus } from '../types/task';
import { Check, Edit3, Trash2 } from 'lucide-vue-next';

const props = defineProps<{
  task: Task;
  x: number;
  y: number;
}>();

const emit = defineEmits<{
  (e: 'close'): void;
}>();

const taskStore = useTaskStore();

const positionStyle = computed(() => {
  const maxH = typeof window !== 'undefined' ? window.innerHeight : 800;
  const maxW = typeof window !== 'undefined' ? window.innerWidth : 1200;
  return {
    top: `${Math.min(props.y, maxH - 200)}px`,
    left: `${Math.min(props.x, maxW - 200)}px`,
  };
});

function handleStatus(s: TaskStatus) {
  taskStore.setStatus(props.task.id, s);
  emit('close');
}

function handlePriority(p: TaskPriority) {
  taskStore.setPriority(props.task.id, p);
  emit('close');
}

function handleEdit() {
  taskStore.startEditing(props.task.id);
  emit('close');
}

function handleDelete() {
  taskStore.deleteTask(props.task.id);
  emit('close');
}

function handleGlobalClick() {
  emit('close');
}

onMounted(() => {
  window.addEventListener('click', handleGlobalClick);
});

onUnmounted(() => {
  window.removeEventListener('click', handleGlobalClick);
});
</script>

<template>
  <div
    class="fixed z-50 bg-zinc-950 border border-zinc-800 rounded-xl p-1.5 shadow-2xl text-xs font-mono w-48 animate-in fade-in duration-75"
    :style="positionStyle"
    @click.stop
  >
    <div class="px-2 py-1 text-[10px] text-zinc-500 font-bold border-b border-zinc-900 mb-1">
      {{ task.id }}
    </div>

    <!-- Status Actions -->
    <button
      type="button"
      class="w-full text-left px-2 py-1.5 rounded hover:bg-zinc-900 text-zinc-300 flex items-center gap-2 cursor-pointer"
      @click="handleStatus('DONE')"
    >
      <Check class="w-3.5 h-3.5 text-emerald-400" />
      <span>Mark DONE</span>
    </button>
    <button
      type="button"
      class="w-full text-left px-2 py-1.5 rounded hover:bg-zinc-900 text-zinc-300 flex items-center gap-2 cursor-pointer"
      @click="handleStatus('IN_PROGRESS')"
    >
      <span class="w-2 h-2 rounded-full bg-sky-400"></span>
      <span>Set In Progress</span>
    </button>
    <button
      type="button"
      class="w-full text-left px-2 py-1.5 rounded hover:bg-zinc-900 text-zinc-300 flex items-center gap-2 cursor-pointer"
      @click="handleStatus('BLOCKED')"
    >
      <span class="w-2 h-2 rounded-full bg-rose-400"></span>
      <span>Set Blocked</span>
    </button>

    <div class="my-1 border-t border-zinc-900"></div>

    <!-- Edit / Rename -->
    <button
      type="button"
      class="w-full text-left px-2 py-1.5 rounded hover:bg-zinc-900 text-zinc-300 flex items-center gap-2 cursor-pointer"
      @click="handleEdit"
    >
      <Edit3 class="w-3.5 h-3.5 text-zinc-400" />
      <span>Rename Title</span>
    </button>

    <!-- Priority Submenu -->
    <div class="px-2 py-1 text-[10px] text-zinc-500 font-bold border-t border-zinc-900 mt-1">
      Priority:
    </div>
    <div class="grid grid-cols-4 gap-1 px-1 py-0.5">
      <button
        v-for="p in (['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'] as TaskPriority[])"
        :key="p"
        type="button"
        class="text-[9px] py-0.5 rounded border border-zinc-800 hover:bg-zinc-900 text-center text-zinc-300 cursor-pointer"
        @click="handlePriority(p)"
      >
        {{ p.slice(0, 3) }}
      </button>
    </div>

    <div class="my-1 border-t border-zinc-900"></div>

    <!-- Delete -->
    <button
      type="button"
      class="w-full text-left px-2 py-1.5 rounded hover:bg-rose-950/40 text-rose-400 flex items-center gap-2 cursor-pointer"
      @click="handleDelete"
    >
      <Trash2 class="w-3.5 h-3.5 text-rose-400" />
      <span>Delete Task</span>
    </button>
  </div>
</template>
