// source/frontend/components/WeeklySummaryModal.vue
<script setup lang="ts">
import { ref, computed, onMounted } from 'vue';
import { api } from '../services/api';
import { useTaskStore } from '../stores/taskStore';
import { Sparkles, X, Copy, Check, RefreshCw, AlertCircle, CheckCircle2, AlertTriangle, ArrowRight } from 'lucide-vue-next';

defineProps<{
  onClose: () => void;
}>();

const summaryText = ref<string>('');
const isLoading = ref<boolean>(true);
const isCopied = ref<boolean>(false);
const errorMsg = ref<string | null>(null);

interface ParsedSection {
  title: string;
  type: 'overview' | 'blockers' | 'priorities' | 'general';
  items: string[];
}

const parsedSections = computed<ParsedSection[]>(() => {
  if (!summaryText.value) return [];
  const text = summaryText.value;
  const sections: ParsedSection[] = [];
  const rawBlocks = text.split(/(?=###|\*\*\d+\.)/g);

  for (const block of rawBlocks) {
    const trimmed = block.trim();
    if (!trimmed) continue;

    // Detect section title
    let title = '';
    let type: ParsedSection['type'] = 'general';
    const lines = trimmed.split('\n').map((l) => l.trim()).filter(Boolean);
    const firstLine = lines[0] || '';

    if (firstLine.includes('Tổng quan') || firstLine.includes('Overview') || firstLine.includes('Tiến độ')) {
      title = firstLine.replace(/^[#*\d.\s]+/, '').replace(/[:*#]+$/, '').trim();
      type = 'overview';
    } else if (firstLine.includes('Rủi ro') || firstLine.includes('Blocker') || firstLine.includes('Điểm nghẽn')) {
      title = firstLine.replace(/^[#*\d.\s]+/, '').replace(/[:*#]+$/, '').trim();
      type = 'blockers';
    } else if (firstLine.includes('Ưu tiên') || firstLine.includes('Priority') || firstLine.includes('Việc cần')) {
      title = firstLine.replace(/^[#*\d.\s]+/, '').replace(/[:*#]+$/, '').trim();
      type = 'priorities';
    } else {
      title = firstLine.replace(/^[#*\d.\s]+/, '').replace(/[:*#]+$/, '').trim();
    }

    const items = lines.slice(1).map((l) => l.replace(/^[-*•\d.]+\s*/, '').replace(/\*\*/g, '').trim()).filter(Boolean);

    if (title || items.length > 0) {
      sections.push({
        title: title || 'Chi tiết báo cáo',
        type,
        items: items.length > 0 ? items : [trimmed.replace(/^[#*\d.\s]+/, '').replace(/\*\*/g, '')],
      });
    }
  }

  return sections.length > 0
    ? sections
    : [
        {
          title: 'Chi tiết báo cáo',
          type: 'general',
          items: text.split('\n').map((l) => l.replace(/^[-*•\d.]+\s*/, '').replace(/\*\*/g, '').trim()).filter(Boolean),
        },
      ];
});

const taskStore = useTaskStore();

async function loadSummary() {
  const projectId = taskStore.currentProjectId;
  if (projectId === null) {
    errorMsg.value = 'Select a project first.';
    return;
  }
  isLoading.value = true;
  errorMsg.value = null;
  try {
    const res = await api.getWeeklySummary(projectId);
    summaryText.value = res.summary;
  } catch (e: any) {
    errorMsg.value = e.message || 'Failed to generate weekly summary';
  } finally {
    isLoading.value = false;
  }
}

async function handleCopy() {
  try {
    if (navigator.clipboard && window.isSecureContext) {
      await navigator.clipboard.writeText(summaryText.value);
    } else {
      const textarea = document.createElement('textarea');
      textarea.value = summaryText.value;
      textarea.style.position = 'fixed';
      textarea.style.left = '-9999px';
      textarea.style.top = '0';
      document.body.appendChild(textarea);
      textarea.focus();
      textarea.select();
      document.execCommand('copy');
      document.body.removeChild(textarea);
    }
    isCopied.value = true;
    setTimeout(() => (isCopied.value = false), 2000);
  } catch (err) {
    console.error('Failed to copy to clipboard:', err);
  }
}

onMounted(() => {
  loadSummary();
});
</script>

<template>
  <div
    class="fixed inset-0 z-50 bg-slate-900/40 dark:bg-black/75 backdrop-blur-xs flex items-center justify-center p-3 md:p-6"
    @click.self="onClose"
  >
    <div class="bg-white dark:bg-slate-900 w-full max-w-2xl rounded-lg p-5 md:p-6 shadow-2xl border border-slate-300 dark:border-slate-800 text-slate-900 dark:text-slate-100 flex flex-col max-h-[85vh]">
      <!-- Header -->
      <div class="flex items-center justify-between pb-3 border-b border-slate-200 dark:border-slate-800">
        <div class="flex items-center gap-2.5">
          <div class="p-2 rounded-md bg-indigo-50 dark:bg-indigo-500/10 border border-indigo-200 dark:border-indigo-500/30 text-indigo-600 dark:text-indigo-400">
            <Sparkles class="w-5 h-5" />
          </div>
          <div>
            <h2 class="text-sm md:text-base font-semibold text-slate-900 dark:text-slate-100 font-sans">Weekly Progress Summary</h2>
            <p class="text-[11px] text-slate-500 dark:text-slate-400">Status, blockers, and sprint priority overview</p>
          </div>
        </div>
        <button type="button" class="p-1.5 hover:bg-slate-100 dark:hover:bg-slate-800 rounded-md text-slate-400 hover:text-slate-600 dark:hover:text-slate-200 cursor-pointer" @click="onClose">
          <X class="w-5 h-5" />
        </button>
      </div>

      <!-- Body -->
      <div class="flex-1 overflow-y-auto py-4 space-y-3.5 text-xs">
        <div v-if="isLoading" class="flex flex-col items-center justify-center py-16 text-center">
          <RefreshCw class="w-6 h-6 text-indigo-600 dark:text-indigo-400 animate-spin mb-3" />
          <p class="text-xs text-slate-500 dark:text-slate-400 font-mono">Aggregating live task data & generating report...</p>
        </div>

        <div v-else-if="errorMsg" class="p-4 rounded-lg bg-rose-50 dark:bg-rose-950/40 border border-rose-200 dark:border-rose-800 text-rose-700 dark:text-rose-300 flex items-center gap-2 font-mono">
          <AlertCircle class="w-4 h-4 shrink-0" />
          <span>{{ errorMsg }}</span>
        </div>

        <!-- Structured Rendered Output -->
        <div v-else class="space-y-3">
          <div
            v-for="(sec, sIdx) in parsedSections"
            :key="sIdx"
            class="p-3.5 rounded-lg border flex flex-col gap-2"
            :class="sec.type === 'blockers'
              ? 'bg-rose-50/60 dark:bg-rose-950/20 border-rose-200 dark:border-rose-900/40'
              : sec.type === 'priorities'
              ? 'bg-amber-50/60 dark:bg-amber-950/20 border-amber-200 dark:border-amber-900/40'
              : 'bg-slate-50 dark:bg-slate-900/60 border-slate-200 dark:border-slate-800'"
          >
            <!-- Section Header -->
            <div class="flex items-center gap-2">
              <AlertTriangle v-if="sec.type === 'blockers'" class="w-4 h-4 text-rose-600 dark:text-rose-400" />
              <ArrowRight v-else-if="sec.type === 'priorities'" class="w-4 h-4 text-amber-600 dark:text-amber-400" />
              <CheckCircle2 v-else class="w-4 h-4 text-indigo-600 dark:text-indigo-400" />
              <h3 class="font-mono font-bold text-xs uppercase tracking-wider text-slate-900 dark:text-slate-100">
                {{ sec.title }}
              </h3>
            </div>

            <!-- Bullet Items -->
            <ul class="space-y-1.5 pl-6 list-disc font-sans text-slate-700 dark:text-slate-300 leading-relaxed text-xs">
              <li v-for="(item, iIdx) in sec.items" :key="iIdx">
                {{ item }}
              </li>
            </ul>
          </div>
        </div>
      </div>

      <!-- Footer -->
      <div class="pt-3 border-t border-slate-200 dark:border-slate-800 flex items-center justify-between">
        <button
          type="button"
          class="h-8 inline-flex items-center gap-1.5 px-3 rounded-md bg-slate-100 dark:bg-slate-900 hover:bg-slate-200 dark:hover:bg-slate-800 border border-slate-200 dark:border-slate-800 text-slate-700 dark:text-slate-300 font-mono text-xs cursor-pointer"
          @click="loadSummary"
          :disabled="isLoading"
        >
          <RefreshCw class="w-3.5 h-3.5" :class="isLoading ? 'animate-spin' : ''" />
          <span>Regenerate</span>
        </button>

        <button
          type="button"
          class="h-8 inline-flex items-center gap-1.5 px-3.5 rounded-md bg-slate-900 dark:bg-slate-100 hover:bg-slate-800 dark:hover:bg-white text-white dark:text-slate-950 font-mono font-medium text-xs cursor-pointer shadow-xs"
          @click="handleCopy"
          :disabled="isLoading || !summaryText"
        >
          <Check v-if="isCopied" class="w-3.5 h-3.5 text-emerald-400" />
          <Copy v-else class="w-3.5 h-3.5" />
          <span>{{ isCopied ? 'Copied!' : 'Copy Report' }}</span>
        </button>
      </div>
    </div>
  </div>
</template>

// src/components/WeeklySummaryModal.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { api } from '../services/api';
  import { Sparkles, X, Copy, Check, RefreshCw, AlertCircle } from 'lucide-svelte';

  interface Props {
    onClose: () => void;
  }

  let { onClose }: Props = $props();

  let summaryText = $state<string>('');
  let isLoading = $state<boolean>(true);
  let isCopied = $state<boolean>(false);
  let errorMsg = $state<string | null>(null);

  async function loadSummary() {
    isLoading = true;
    errorMsg = null;
    try {
      const res = await api.getWeeklySummary(1);
      summaryText = res.summary;
    } catch (e: any) {
      errorMsg = e.message || 'Failed to generate weekly summary';
    } finally {
      isLoading = false;
    }
  }

  function handleCopy() {
    navigator.clipboard.writeText(summaryText);
    isCopied = true;
    setTimeout(() => (isCopied = false), 2000);
  }

  onMount(() => {
    loadSummary();
  });
</script>

<div class="fixed inset-0 z-50 bg-black/75 backdrop-blur-sm flex items-center justify-center p-3 md:p-6 animate-in fade-in duration-100">
  <div class="glass-panel w-full max-w-2xl rounded-2xl p-5 md:p-6 shadow-2xl border border-zinc-700/60 text-zinc-100 flex flex-col max-h-[85vh]">
    <!-- Header -->
    <div class="flex items-center justify-between pb-3 border-b border-zinc-800">
      <div class="flex items-center gap-2.5">
        <div class="p-2 rounded-xl bg-indigo-500/10 border border-indigo-500/30 text-indigo-400">
          <Sparkles class="w-5 h-5" />
        </div>
        <div>
          <h2 class="text-sm md:text-base font-bold text-zinc-100 font-mono">Weekly Project Progress Summary</h2>
          <p class="text-[11px] text-zinc-400">Mandated Feature A: Status & risk report generation</p>
        </div>
      </div>
      <button class="p-1.5 hover:bg-zinc-800 rounded-lg text-zinc-400 hover:text-zinc-200 cursor-pointer" onclick={onClose}>
        <X class="w-5 h-5" />
      </button>
    </div>

    <!-- Body -->
    <div class="flex-1 overflow-y-auto py-4 space-y-3 text-xs">
      {#if isLoading}
        <div class="flex flex-col items-center justify-center py-16 text-center">
          <RefreshCw class="w-6 h-6 text-indigo-400 animate-spin mb-3" />
          <p class="text-xs text-zinc-400 font-mono">Aggregating live task data & generating AI report...</p>
        </div>
      {:else if errorMsg}
        <div class="p-4 rounded-xl bg-rose-950/40 border border-rose-800 text-rose-300 flex items-center gap-2 font-mono">
          <AlertCircle class="w-4 h-4 shrink-0" />
          <span>{errorMsg}</span>
        </div>
      {:else}
        <div class="p-4 rounded-xl bg-zinc-900/80 border border-zinc-800 whitespace-pre-wrap font-sans text-zinc-200 leading-relaxed text-xs">
          {summaryText}
        </div>
      {/if}
    </div>

    <!-- Footer -->
    <div class="pt-3 border-t border-zinc-800 flex items-center justify-between">
      <button
        type="button"
        class="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-zinc-900 hover:bg-zinc-800 border border-zinc-800 text-zinc-300 font-mono text-xs cursor-pointer transition"
        onclick={loadSummary}
        disabled={isLoading}
      >
        <RefreshCw class="w-3.5 h-3.5 {isLoading ? 'animate-spin' : ''}" />
        <span>Regenerate</span>
      </button>

      <div class="flex items-center gap-2">
        <button
          type="button"
          class="inline-flex items-center gap-1.5 px-3.5 py-1.5 rounded-lg bg-zinc-100 hover:bg-white text-zinc-950 font-mono font-medium text-xs cursor-pointer transition"
          onclick={handleCopy}
          disabled={isLoading || !summaryText}
        >
          {#if isCopied}
            <Check class="w-3.5 h-3.5 text-emerald-600" />
            <span>Copied!</span>
          {:else}
            <Copy class="w-3.5 h-3.5" />
            <span>Copy Report</span>
          {/if}
        </button>
      </div>
    </div>
  </div>
</div>
